#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Long;
use MHA::AWS::MasterIpFailover;
use JSON;

my (
    $orig_master_host, $orig_master_ip, $orig_master_port,
    $new_master_host, $new_master_ip, $new_master_port,
    $command, $ssh_user, $interface_name,
);
GetOptions(
    "interface_name=s"      => \$interface_name,
    "orig_master_host=s"    => \$orig_master_host,
    "orig_master_ip=s"      => \$orig_master_ip,
    "orig_master_port=s"    => \$orig_master_port,
    "new_master_host=s"     => \$new_master_host,
    "new_master_ip=s"       => \$new_master_ip,
    "new_master_port=s"     => \$new_master_port,
    "new_master_password=s" => \$new_master_password,
    "ssh_user=s"            => \$ssh_user,
    "command=s"             => \$command,
);
my $app = MHA::AWS::MasterIpFailover->new(
    orig_master_host => $orig_master_host,
    new_master_host  => $new_master_host,
    interface_name   => $interface_name,
);
$app->init;
print JSON->new->pretty->encode($app->info);
$app->dispatch($command);

exit 0;

__END__

=pod

=head1 USAGE

    $ master_ip_failover --interface_name=mha-vip --command=[command from MHA] ...

    --interface_name=[Description of ENI]
=cut
